all: q1 q2 q3 q5 q7

clean:
	rm -f q1 q2 q3 q5 q7

q1: question1.c
	gcc -o q1 question1.c -Wall

q2: question2.c
	gcc -o q2 question2.c -Wall

q3: question3.c
	gcc -o q3 question3.c -Wall

q5: question5.c
	gcc -o q5 question5.c -Wall

q7: question7.c
	gcc -o q7 question7.c -Wall
